name: Deploy to Azure-webapps

env:
  WEBAPP_NAME: bar-api
  PACKAGE_PATH: ${{ github.workspace }}
  JAVA_VERSION: '11'
  SUBSCRIPTION_ID: ${{ secrets.azureWebappSubscriptionId }}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK ${{ env.JAVA_VERSION }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    
    - name: Generate open-api JSON file from Java project
      run: |
        cd bar-api
        mvn integration-test --file pom.xml
    
    - name: Set up node
      uses: actions/setup-node@v2.1.2
    
    - name: Install Angular project npm dependencies
      run: |
        cd angular-clients
        npm i -g @angular/cli @ionic/cli
        npm i
    
    - name: Build Angular app for web deployment
      run: |
        cd angular-clients
        ionic build -c=prod-web
    
    - name: Build bar-api Java project
      run: |
        cd bar-api
        mvn package --file pom.xml
    
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.WEBAPP_NAME }}
        publish-profile: ${{ env.SUBSCRIPTION_ID }}
        package: '${{ env.PACKAGE_PATH }}/target/*.jar'
